/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as protectedOrdersIndexRouteImport } from './routes/(protected)/orders/index'
import { Route as protectedFoodsIndexRouteImport } from './routes/(protected)/foods/index'
import { Route as protectedCategoriesIndexRouteImport } from './routes/(protected)/categories/index'
import { Route as protectedOrdersOrderIdRouteImport } from './routes/(protected)/orders/$orderId'
import { Route as protectedFoodsFoodIdRouteImport } from './routes/(protected)/foods/$foodId'
import { Route as protectedCategoriesCategoryIdRouteImport } from './routes/(protected)/categories/$categoryId'

const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const protectedOrdersIndexRoute = protectedOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedFoodsIndexRoute = protectedFoodsIndexRouteImport.update({
  id: '/foods/',
  path: '/foods/',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedCategoriesIndexRoute =
  protectedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => protectedRouteRoute,
  } as any)
const protectedOrdersOrderIdRoute = protectedOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedFoodsFoodIdRoute = protectedFoodsFoodIdRouteImport.update({
  id: '/foods/$foodId',
  path: '/foods/$foodId',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedCategoriesCategoryIdRoute =
  protectedCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => protectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof protectedDashboardRoute
  '/categories/$categoryId': typeof protectedCategoriesCategoryIdRoute
  '/foods/$foodId': typeof protectedFoodsFoodIdRoute
  '/orders/$orderId': typeof protectedOrdersOrderIdRoute
  '/categories': typeof protectedCategoriesIndexRoute
  '/foods': typeof protectedFoodsIndexRoute
  '/orders': typeof protectedOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof protectedDashboardRoute
  '/categories/$categoryId': typeof protectedCategoriesCategoryIdRoute
  '/foods/$foodId': typeof protectedFoodsFoodIdRoute
  '/orders/$orderId': typeof protectedOrdersOrderIdRoute
  '/categories': typeof protectedCategoriesIndexRoute
  '/foods': typeof protectedFoodsIndexRoute
  '/orders': typeof protectedOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(protected)/categories/$categoryId': typeof protectedCategoriesCategoryIdRoute
  '/(protected)/foods/$foodId': typeof protectedFoodsFoodIdRoute
  '/(protected)/orders/$orderId': typeof protectedOrdersOrderIdRoute
  '/(protected)/categories/': typeof protectedCategoriesIndexRoute
  '/(protected)/foods/': typeof protectedFoodsIndexRoute
  '/(protected)/orders/': typeof protectedOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/categories/$categoryId'
    | '/foods/$foodId'
    | '/orders/$orderId'
    | '/categories'
    | '/foods'
    | '/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/categories/$categoryId'
    | '/foods/$foodId'
    | '/orders/$orderId'
    | '/categories'
    | '/foods'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(protected)'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(protected)/dashboard'
    | '/(protected)/categories/$categoryId'
    | '/(protected)/foods/$foodId'
    | '/(protected)/orders/$orderId'
    | '/(protected)/categories/'
    | '/(protected)/foods/'
    | '/(protected)/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(protected)/orders/': {
      id: '/(protected)/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof protectedOrdersIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/foods/': {
      id: '/(protected)/foods/'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof protectedFoodsIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/categories/': {
      id: '/(protected)/categories/'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof protectedCategoriesIndexRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/orders/$orderId': {
      id: '/(protected)/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof protectedOrdersOrderIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/foods/$foodId': {
      id: '/(protected)/foods/$foodId'
      path: '/foods/$foodId'
      fullPath: '/foods/$foodId'
      preLoaderRoute: typeof protectedFoodsFoodIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/categories/$categoryId': {
      id: '/(protected)/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof protectedCategoriesCategoryIdRouteImport
      parentRoute: typeof protectedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface protectedRouteRouteChildren {
  protectedDashboardRoute: typeof protectedDashboardRoute
  protectedCategoriesCategoryIdRoute: typeof protectedCategoriesCategoryIdRoute
  protectedFoodsFoodIdRoute: typeof protectedFoodsFoodIdRoute
  protectedOrdersOrderIdRoute: typeof protectedOrdersOrderIdRoute
  protectedCategoriesIndexRoute: typeof protectedCategoriesIndexRoute
  protectedFoodsIndexRoute: typeof protectedFoodsIndexRoute
  protectedOrdersIndexRoute: typeof protectedOrdersIndexRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedDashboardRoute: protectedDashboardRoute,
  protectedCategoriesCategoryIdRoute: protectedCategoriesCategoryIdRoute,
  protectedFoodsFoodIdRoute: protectedFoodsFoodIdRoute,
  protectedOrdersOrderIdRoute: protectedOrdersOrderIdRoute,
  protectedCategoriesIndexRoute: protectedCategoriesIndexRoute,
  protectedFoodsIndexRoute: protectedFoodsIndexRoute,
  protectedOrdersIndexRoute: protectedOrdersIndexRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  protectedRouteRoute: protectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
